/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminOfficesImport } from './routes/admin/offices'
import { Route as AdminOfficesIndexImport } from './routes/admin/offices/index'
import { Route as AdminOfficesOfficeIdImport } from './routes/admin/offices/$officeId'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOfficesRoute = AdminOfficesImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOfficesIndexRoute = AdminOfficesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOfficesRoute,
} as any)

const AdminOfficesOfficeIdRoute = AdminOfficesOfficeIdImport.update({
  id: '/$officeId',
  path: '/$officeId',
  getParentRoute: () => AdminOfficesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/offices': {
      id: '/admin/offices'
      path: '/offices'
      fullPath: '/admin/offices'
      preLoaderRoute: typeof AdminOfficesImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/offices/$officeId': {
      id: '/admin/offices/$officeId'
      path: '/$officeId'
      fullPath: '/admin/offices/$officeId'
      preLoaderRoute: typeof AdminOfficesOfficeIdImport
      parentRoute: typeof AdminOfficesImport
    }
    '/admin/offices/': {
      id: '/admin/offices/'
      path: '/'
      fullPath: '/admin/offices/'
      preLoaderRoute: typeof AdminOfficesIndexImport
      parentRoute: typeof AdminOfficesImport
    }
  }
}

// Create and export the route tree

interface AdminOfficesRouteChildren {
  AdminOfficesOfficeIdRoute: typeof AdminOfficesOfficeIdRoute
  AdminOfficesIndexRoute: typeof AdminOfficesIndexRoute
}

const AdminOfficesRouteChildren: AdminOfficesRouteChildren = {
  AdminOfficesOfficeIdRoute: AdminOfficesOfficeIdRoute,
  AdminOfficesIndexRoute: AdminOfficesIndexRoute,
}

const AdminOfficesRouteWithChildren = AdminOfficesRoute._addFileChildren(
  AdminOfficesRouteChildren,
)

interface AdminRouteChildren {
  AdminOfficesRoute: typeof AdminOfficesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOfficesRoute: AdminOfficesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/offices': typeof AdminOfficesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/offices/$officeId': typeof AdminOfficesOfficeIdRoute
  '/admin/offices/': typeof AdminOfficesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/offices/$officeId': typeof AdminOfficesOfficeIdRoute
  '/admin/offices': typeof AdminOfficesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/offices': typeof AdminOfficesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/offices/$officeId': typeof AdminOfficesOfficeIdRoute
  '/admin/offices/': typeof AdminOfficesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/offices'
    | '/admin/'
    | '/admin/offices/$officeId'
    | '/admin/offices/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/offices/$officeId' | '/admin/offices'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/offices'
    | '/admin/'
    | '/admin/offices/$officeId'
    | '/admin/offices/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/offices",
        "/admin/"
      ]
    },
    "/admin/offices": {
      "filePath": "admin/offices.tsx",
      "parent": "/admin",
      "children": [
        "/admin/offices/$officeId",
        "/admin/offices/"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/offices/$officeId": {
      "filePath": "admin/offices/$officeId.tsx",
      "parent": "/admin/offices"
    },
    "/admin/offices/": {
      "filePath": "admin/offices/index.tsx",
      "parent": "/admin/offices"
    }
  }
}
ROUTE_MANIFEST_END */
